lib/beaker-answers/versions/version20161.rb

This is just to get the initial pipelines up and running; there are no
answers new to 2016.1 yet, so it will just inherit the_answers generated
by Version20153.

(BKR-549) Add answers for 2016.1

---

lib/beaker-answers/versions/version20153.rb

Currently in integration CI all installs are not setting the
q_use_application_services answer. When that answer is set to nothing
the pe-classification script does not enable application services.
This PR will cause at least the pre-upgrade integration to fail. This is probably okay for now because it is actually exposing a legitimate bug and should be merged in regardless of the state of this job.

(maint) Add q_use_application_services question

---

lib/beaker-answers/versions/version20153.rb
spec/beaker-answers/beaker-answers_spec.rb

Both the master and console must be given the
`q_use_application_services` answer, since the console
needs to know that it needs classify the orchestrator.

(PE-12849) Add q_use_application_services to console

---

lib/beaker-answers/answers.rb
lib/beaker-answers/versions/upgrade.rb
lib/beaker-answers/versions/upgrade38.rb
spec/beaker-answers/beaker-answers_spec.rb

Previous to this commit, answer files were generated in full during
upgrade scenarios; this does not match the user workflow or what is
documented for upgrades, so we should only supply answers needed. The
answers `create` method now checks the `:type` in options and creates a
separate branch of `Answers` named `Upgrade`.
This change only affects PE 3.8 and higher; all lower versions will
continue to produce an entire answers file.

(BKR-763) Supply only necessary answers on upgrade

---

lib/beaker-answers/versions/version20162.rb
spec/beaker-answers/beaker-answers_spec.rb

To allow SSL cert based auth in the new installer while maintaining the legacy
bash script, the console node now needs to know about the orchestrator database user
and name if they are specified to be non default

(PE-14877) Pass in orchestrator db to console

---

lib/beaker-answers/answers.rb
lib/beaker-answers/versions/upgrade.rb
lib/beaker-answers/versions/upgrade38.rb
lib/beaker-answers/versions/version30.rb
spec/beaker-answers/beaker-answers_spec.rb
spec/beaker-answers/upgrade_spec.rb
spec/helpers.rb

This PR specifically targets answers for upgrading to PE 3.8.x. It adds
a new subclassed branch directly from `Answers` and looks for the
`options[:type][:upgrade]` option from beaker. All other upgrade types
will continue to create full answer sets.

(BKR-763) Add upgrade answers for PE 3.8.x

---

lib/beaker-answers/versions/version20162.rb
spec/beaker-answers/versions/version20162_spec.rb

Previous to this commit, answer generation for 2016.2 would generate a
list of parameters on the puppet_enterprise for both mono and split. Due
to changes introduced in Puppet 4.4, the puppet_enterprsie module no
longer needs all host parameters in a monolithic install case.
This commit updates the generation to match what the module has changed
to use. For a monolithic install, the only required answers are now the
console admin password, and puppet_master_host. for split installs with
PE postgres, just master, console and puppetdb host.

(PE-16028) Update required answers for 2016.2

---

beaker-answers.gemspec

hocon < 1 is not compatible with infraspec 2.59.1.  This push it to ~1.0
to match beaker declaration and have infraspec working again.

(ENTERPRISE-910) Unpin hocon

---

lib/beaker-answers/versions/upgrade38.rb

Before this commit the puppetdb hostname answer would fallback to being
an ip address which would cause the installer to do incorrect things as
we depend on those answers to be hostnames for certificate generation
and configuration bootstrap purposes.
This commit changes the q_puppetdb_hostname answer to be the hostname of
the puppetdb node instead of its ip address which is returned by the
reachable_name method on the host object.

(PE-16065) Do not fall back to ip address when setting puppetdb hostname

---

lib/beaker-answers/versions/version20163.rb
spec/beaker-answers/versions/version20163_spec.rb

`puppet_enterprise::use_application_services` is deprecated in 2016.3.x,
so we should no longer specify it.

(PE-16772) Remove app_orch from 20163x answers

---

lib/beaker-answers.rb
lib/beaker-answers/pe_conf.rb
lib/beaker-answers/versions/version20162.rb
lib/beaker-answers/versions/version20171.rb
lib/beaker-answers/versions/version20172.rb
spec/beaker-answers/pe_conf_spec.rb
spec/beaker-answers/versions/version20171_spec.rb
spec/beaker-answers/versions/version20172_spec.rb
spec/shared/context.rb

and prepare Glisan.
Generate a meep 2.0 format based on version flag ￼…
Previously there was a hard version break set on PE 2017.1 which would
produce a 2.0 format pe.conf, but since we've had to back out meep
classification in Flanders, this needs to change.
Added a PeConf object to generate 1.0 and 2.0 format files based on a
meep_schema_version flag. It defaults to the original 1.0 format. It
will be up to beaker-pe to submit this flag in the beaker options based
on its use_meep_for_classification?() test.
There is one change to the 1.0 hiera_host_config implementation in that
it no longer uses answer_for to set the master, db, console settings. I
don't think this matters because there are no defaults for these
settings, and beaker answer overrides are merged afterwards in …

(PE-19203,PE-16706) Revert meep classification from Flanders

---

lib/beaker-answers/pe_conf.rb
spec/beaker-answers/pe_conf_spec.rb

Before this commit the pe_repo platform class that would be generated
for all windows platforms would be incorrect as there is only a single
windows puppet agent. When this method would generate the list of
platform classes windows would be incorrect.
This commit ensures that when windows is a platform on a host we return
one of the two possible windows pe_repo platform classes.

(PE-19948) Fix pe_repo platform class for windows

---

lib/beaker-answers/versions/version20172.rb
spec/shared/context.rb

When generating meep 2.0 answers.
Changes in version20162.rb took an answers structure like:
```yaml
:answers
puppet_enterprise:
profile:
"master::foo": bar
```
and produce a pe.conf with
"puppet_enterprise::profile::master::foo": "bar"
This might be a convenience for some kinds of parameter listing, but
breaks your ability to submit actually structured data such as:
```yaml
:answers
feature_flags:
pe_modules_next: true
```
Where feature_flags is supposed to be a hash, and not a parameter.
This pr takes the approach of just fixing new behavior in Glisan, when
using Meep 2.0 format (pe-modules-next), but it might be better to
change the behavior altogether, although this is a breaking change for
anyone relying on the previous 'helpful' collapsing of answer elements.

(maint) Do not flatten answers

---

lib/beaker-answers/pe_conf.rb
spec/beaker-answers/pe_conf_spec.rb

This PR adds support for PE managed postgres support.
It detects for a new role: pe_postgres.
If that role is found, that node will be set as the puppetdb PE node.
Then there will be a check for how to configure the postgres node.
Either way SSL or with password, depending on options supplied.
The meep 2.0 settings are a bit of work in progress, future work
will probably be required to get them just right.

(PE-22724) Add PE managed postgres support

---

lib/beaker-answers/pe_conf.rb
spec/beaker-answers/pe_conf_spec.rb

This setting was left out in my previous commit. Without this setting
on a monolithic install with PE managed external postgres, the
puppet database takes too long (25 minutes+) to time out. This causes
failures in Jenkins.
This answer that is added in will make the timeout only a few minutes
so hopefuly Jenkins wont abort the job.

(PE-22724) Add puppetdb startout timer for external postgres

---

lib/beaker-answers/pe_conf.rb
spec/beaker-answers/pe_conf_spec.rb

This PR sets both puppet_enterprise::database_ssl and puppet_enterprise::database_cert_auth
to be false for the PE managed password postgres.
With a recent change in PE 2017.3.x this is now required or there will be warnings in the
installer log which will cause testing failures.

(PE-22857) Add SSL settings to external postgres answers

---

lib/beaker-answers/pe_conf.rb
spec/beaker-answers/pe_conf_spec.rb

This PR sets databsae ssl and cert auth to true. This is required
for PE managed postgres installations.

(PE_22857) Set SSL settings to true for postgres

---

lib/beaker-answers/pe_conf.rb

When setting up external postgres node use ssl based cert auth as the
default instead of password based auth

PE-25811 Use ssl based auth as default for external postgres node

---

beaker-answers.gemspec

Removing markdown from depndencies as this is not currently used. With
markdown, unit tests are failing in jenkins with older versions of ruby
that can't handle markdown's dependencies.

Remove markdown dependency

---

README.md
lib/beaker-answers/versions/version20173.rb
spec/beaker-answers/versions/version20173_spec.rb

A patch was made so that beaker-answers would support any version past 2017.3 without requiring changes to this library each time a new release was created. However, the regex used to detect versions up to 9999.9.99 caused it to also match pre-2017.3 versions, which could cause unsupported answers to be used. This constrains the version checking to limit the maximum version to 2099.9.99. We'll probably all be dead by then, along with this code.

(maint) Fix overly permissive version checking and update README.md

---

.github/workflows/release.yml

We don't need autogenerated release notes for this repo so this action input should not be included.

(maint) remove optional 'bodyfile' input from release workflow
